In [ ]:
import numpy as np

    #crear una matriz 
print("matriz de una dimension \n Matriz a=")
a = np.array([1,2,3,4,5])
print(a)
print("")



    #operaciones basicas
print("suma 5 a cada elemento de la matriz a")
print(a+5)           #suma 5 a cada elemento
print("multiplica por 5 cada elemento de la matriz a")
print(a *5)          #multiplica por 5 cada elemento
print("")



    #crear un matriz de dos dimensiones
print("Matriz de dos dimenciones 2x3\n Matriz b=")
b = np.array([[1,2,3],[4,5,6]])
print(b)
print("")



    #Indexacion
print("Accede a elemento en la segunda[1] fila y tercera columna[2]")
print(b[1,2])        # Accede a elemento en la segunda[1] fila y tercera columna[2]
print("")


    #Funciones matematicas
print("media de los elementos de la matriz b")
print(np.mean(b))     #calcula la media de los elementos
print("")


    #Generacion de los numeros aletorios
print("Generacion de una matriz de 3x3 con numeros aleatoreos entre 0  y 1")

numeros_aleatorios = np.random.rand(3,3)
print(numeros_aleatorios)






RANDOM

In [ ]:
    #numero aletorio entre 1-0
print(np.random.random())
print("")


    #numero aleatorio entero entre un rango de numeros 
print(np.random.randint(1,10))# np.random.randint( Min, Max,) no incluye el rango maximo
print("")


    #numero aleatorio real entre un rango de numeros 
print(np.random.uniform(1,10)) # np.random.uniform( Min, Max,) no incluye el rango maximo
print("")


    #numero aleatorio escogido de un lista o matriz dada
lista= [1,5,10,15,20]
print(np.random.choice(lista)) #np.random.choice(list,size,replace=,p=[])
print("")                      #list=lista 
                               #size = tamaño de matreiz de salida si queremos mas de un elemento
                               #replace= puede ser false o true , si queremos deseamso que los datos de salida pueden ono repetirse 
                               #p=[0.2,0.5,0.3] lista de probabilidades de cada elemento la suma debe dar 1

matriz=np.array([[2,4,6],[8,10,12],[14,16,18]])
print(np.random.choice(matriz.flatten())) #np.random.choice(matriz aplanada)
print("")


    #genera un matriz con numeros aleatorios uniformes(reales)
print(np.random.rand(2,2))   #Matriz de 2x2 con numeros aletorios
print("")
print(np.random.rand(5,3))   #Matriz de 2x2 con numeros aletorios
print("")
print(np.random.uniform(1,10,size=(2,3))) #matrix de 2x3 con numero uniformes de un rango 
print("")


    #genera un matriz con numeros aleatorios enteros entre un rango
print(np.random.randint(1,10,size=(2,3))) #matriz de 2x3 con numeros aletorios enteros en un rango
print("")

    #mezcla aleatoriamento los elemntos de una matriz de una sola dimension 
    #o un lista  en su lugar regresa la matriz modificada
A=np.array([1,2,5,48])
print(A)
np.random.shuffle(A)
print(A)

    #generar numeros aletorios siguiendo una distribucion normal(distribucion gausiana)
    #esta funcion permite especifiscar la media(loc=) la desviacion estandar(scale)y el tamaño de los numeros aletorios 
    #np.random.normal(loc=,scale=,size=None)
media=0.0
desv_estand=1.0
tamaño=10     #10 elementos
numeros_aleatorios=np.random.normal(media,desv_estand,tamaño)
print("numeros aleatorios generados",numeros_aleatorios)



ARRAY

1_creacion de matrices

In [ ]:
import numpy as np

    # crea una  matriz apartir de una lista
A = np.array([[5,8,2],[1,5,9]])
print(A)
print("")

    #crea una matriz con todos los elementos en cero
B = np.zeros((2,3),int) # np.zeros((shape),DataType)
print(B)
print("")

    #crea una matriz con todos los elementos en uno
C = np.ones((3,3),int) # np.ones((shape),DataType)
print(C)
print("")

    #crea una matriz con todos los elementos establecidos en un valor en especifico
D = np.full((3,5),5) #np.full((shape),fill_value)
print(D)
print("")

    #crea una matriz(lineal) con valores de un rango dado con tamaño de paso especifico
E = np.arange(5,20,2) #np.arange(start,stop, tamaño del salto)
print(E)
print("")
    #crea una matriz(lineal)  con una secuencia de numeros que estan distribuidos de 
    #forma uniforme en un rango en especifico 
F = np.linspace(0,100,14)   #np.linspace(start,stop,No_elementos)
print(F)
print("")

    #crea una matriz identidad de tamaño N X N 
   #Una matriz identidad  es cuadrada y la diagonal principal  contiene valores de 1
G = np.eye(5) #np.eye(N)     N=tamaño de la matriz
print(G)
print("")



2_Manipulacion de matrices

In [ ]:
   #cambia la forma de una matriz
A = np.array([5,8,4,7,6,9,8,4])
B = np.array([[2,6,9,7,8],[1,4,8,6,8]])

X = np.array([[5,8,2,6,9],[4,5,6,2,1]])
print(f"Matriz A=\n{A}\n\nMatriz B=\n{B}")
print("")

   #cambia la forma de una matriz
C = np.reshape(A,(2,4))         # np.reshape(Arrey,(shape)) La nueva matriz debe contener el
#print(C)                        #mismo No de elementos
print("")

   #devuelve la copia de una matriz  aplanada
#D=B.flatten()
#print(D)
print("")

   #trasapone la matriz cambia filas por columnas
F=B.transpose()
#print(F)
print("")

   #concatenar matrices a lo largo de un eje en especifico
G = np.concatenate((B,X),axis=1) #axis = 1 se concatenan en el eje de las X 
#print(G)
print("")
H = np.concatenate((B,X),axis=0) #axis = 0 se concatenan en el eje de las Y 
#print(H)
print("")

   # aplilar matrices a lo largo de un eje en especifico
I = np.stack((B,X),axis=1)
print(I)
print("")

J = np.stack((B,X),axis=0)
print(J)
print("")


#divide una matriz en varias submatrices
K=np.split(A,4)
print(K)
print("")


3_ Operaciones aritmeticas

In [ ]:
import numpy as np

A = np.array([[1,3,4],[5,1,3],[1,2,3]])
B = np.array([[2,6,9,7],[1,4,8,6],[5,5,5,5]])
C = np.array([[2,9,7],[1,4,6],[5,5,5]])

print(f"Matriz A=\n{A}\n\nMatriz B=\n{B} \n\nMatriz C=\n{C}")
print("")

#suma de una matrix con un entero
D = A + 5
print(D)
print("")

#suma de dos matrices
E = A + C
print(E)
print("")

#resta de dos matrices
F = A - C
print(F)
print("")







In [ ]:
import numpy as np

A = np.array([[1,3,4],[5,1,3],[1,2,3]])
B = np.array([[2,6,5,7],[1,4,5,8],[5,5,5,5]])
C = np.array([[2,9,7],[1,4,6],[5,5,5]])

print(f"Matriz A=\n{A}\n\nMatriz B=\n{B} \n\nMatriz C=\n{C}")
print("")

#multiplicacion de matrices
G = A*C
print("multiplicacion A X C\n",G)

#multiplicacion de matrices punto a punto 
H = A*C
print("multiplicacion A X C\n",H)
#adicionalmente se pueden usar  funciones para operaciones aritmeticas 
#np.add(array1, array2), np.subtract(array1, array2), np.multiply(array1, array2), np.divide(array1, array2)



operaciones matematicas

In [ ]:
import numpy as np

A = np.array([[1,3,4],[5,1,3],[1,2,3]])
B = np.array([[2,6,5,7],[1,4,5,8],[5,5,5,5]])
C = np.array([[2,9,7],[1,4,6],[5,5,5]])

print(f"Matriz A=\n{A}\n\nMatriz B=\n{B} \n\nMatriz C=\n{C}")
print("")


#calcula la media de los elementos de la matriz
media=np.mean(A)
print(media)
print("")

#calcula la mediana de los elementos 
mediana=np.median(A)
print(mediana)
print("")

#calcula la desviacion estandar de los elementos de la matriz
des_estan=np.std(A)
print(des_estan)
print("")

#calcula la varianza de los elementos
varianza=np.var(A)
print(varianza)
print("")

#calcula la suma de los elementos del array
suma=np.sum(A)
print(suma)



5_ Indexacion y filtrado

In [11]:

import numpy as np

A = np.array([[1,3,4],[5,1,3],[1,2,3]])
B = np.array([[2,6,5,7],[1,4,5,8],[5,5,5,5]])
C = np.array([[2,9,7],[1,4,6],[5,5,5]])

print(f"Matriz A=\n{A}\n\nMatriz B=\n{B} \n\nMatriz C=\n{C}")
print("")

#accede al elemento de una fila (i) y una columna (j)

elemento=A[1,1]
print(elemento)

#accedd a toda la columna j
columna=A[:,1]
print(columna)

#accedd a toda la fila i
fila=A[1,:]
print(fila)

#filtra la matriz segun una condicion booleana
filtrada =A[A<3]
print(filtrada)




Matriz A=
[[1 3 4]
 [5 1 3]
 [1 2 3]]

Matriz B=
[[2 6 5 7]
 [1 4 5 8]
 [5 5 5 5]] 

Matriz C=
[[2 9 7]
 [1 4 6]
 [5 5 5]]

1
[3 1 2]
[5 1 3]
[1 1 1 2]


6_ Modificacion de matriz y mas 

In [24]:

import numpy as np

A = np.array([[1,3,4],[5,1,3],[1,2,3]])
B = np.array([[2,6,5,7],[1,4,5,8],[5,5,5,5]])
b = np.array([[1],[6],[8]])
C = np.array([[2,9,7],[1,4,6],[5,5,5]])

print(f"Matriz A=\n{A}\n\nMatriz B=\n{B} \n\nMatriz C=\n{C}")
print("")

#modificacion de un elemento de la matriz
A[1,1]=100
print(A)
print("")


#multiplicacion formal de matrices 
D=np.dot(A,B)
print(D)

#inversa de una matriz 
a_inv = np.linalg.inv(A)
print(a_inv)
print("")

#determinante de una matriz
a_det=np.linalg.det(A)
print(a_det)
print("")

#resolver un sistema de ecuaciones 

sol_ecuacion=np.linalg.solve(A,b)
print(sol_ecuacion)



print(np.dot(A,a_inv))

Matriz A=
[[1 3 4]
 [5 1 3]
 [1 2 3]]

Matriz B=
[[2 6 5 7]
 [1 4 5 8]
 [5 5 5 5]] 

Matriz C=
[[2 9 7]
 [1 4 6]
 [5 5 5]]

[[  1   3   4]
 [  5 100   3]
 [  1   2   3]]

[[ 25  38  40  51]
 [125 445 540 850]
 [ 19  29  30  38]]
[[-2.88235294  0.00980392  3.83333333]
 [ 0.11764706  0.00980392 -0.16666667]
 [ 0.88235294 -0.00980392 -0.83333333]]

-101.99999999999996

[[27.84313725]
 [-1.15686275]
 [-5.84313725]]
[[ 1.00000000e+00  1.38777878e-17  0.00000000e+00]
 [-4.44089210e-16  1.00000000e+00 -1.11022302e-15]
 [ 0.00000000e+00  1.90819582e-17  1.00000000e+00]]
